-- Clear all data from tables
TRUNCATE TABLE "SyncLog" CASCADE;
TRUNCATE TABLE "SaleItem" CASCADE;
TRUNCATE TABLE "Sale" CASCADE;
TRUNCATE TABLE "Inventory" CASCADE;
TRUNCATE TABLE "Price" CASCADE;
TRUNCATE TABLE "Product" CASCADE;
TRUNCATE TABLE "Store" CASCADE;
